[general]
host = "::"
port = 3000
root = "/public"
log-level = "error"
page-fallback = "/public/index.html"

[advanced]

[[advanced.headers]]
source = "**/*"
[advanced.headers.headers]
Content-Security-Policy = "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; frame-src blob:; object-src blob:; connect-src 'self'; base-uri 'self'; form-action 'none'"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[advanced.headers]]
source = "**/*.{js,css,ttf,woff,woff2,svg,png,jpg}"
[advanced.headers.headers]
Cache-Control = "public, max-age=31536000, immutable"
